
version: "3"

# source: https://github.com/ksindi/kafka-pyspark-demo/blob/master/docker-compose.yml

services:
  wordcount:
    image: bossjones/boss-pyspark-wordcount:latest
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    # source: https://github.com/moby/moby/issues/23910
    # Docker should use the host network DNS server
    extra_hosts:
      - "moby:127.0.0.1"
      - "default:127.0.0.1"
      - "dockerhost:127.0.0.1"
      - "latveria:127.0.0.1"
    volumes:
      - wordcount:/wordcount
    command: true

volumes:
  wordcount:
