
version: "3"

# source: https://github.com/ksindi/kafka-pyspark-demo/blob/master/docker-compose.yml

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    network_mode: host
    ports:
      - "32181:32181"
    expose:
      - "32181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    ports:
      - "29092:29092"
    expose:
      - "29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092

  # spark:
  #   image: jupyter/pyspark-notebook
  #   network_mode: host
  #   links:
  #    - kafka
  #   ports:
  #     - "18888:8888"

# source: https://github.com/sheepkiller/kafka-manager-docker/blob/master/docker-compose.yml
# zookeeper:
#   image: confluent/zookeeper
#   ports:
#     - "2181:2181"

# kafka:
#   image: wurstmeister/kafka:0.9.0.0-1
#   ports:
#     - "9092:9092"
#   links:
#     - zookeeper:zk
#   environment:
#     - KAFKA_ADVERTISED_HOST_NAME
#     - KAFKA_ADVERTISED_PORT=9092
#     - KAFKA_DELETE_TOPIC_ENABLE=true
#     - KAFKA_LOG_RETENTION_HOURS=1
#     - KAFKA_MESSAGE_MAX_BYTES=10000000
#     - KAFKA_REPLICA_FETCH_MAX_BYTES=10000000
#     - KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS=60000
#     - KAFKA_NUM_PARTITIONS=2
#     - KAFKA_DELETE_RETENTION_MS=1000


  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    network_mode: host
    ports:
      - "9000:9000"
    expose:
      - "9000"
    # links:
    #   - zookeeper
    #   - kafka
    environment:
      ZK_HOSTS: localhost:32181
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true
    restart: always
