
version: "3"

# source: https://github.com/ksindi/kafka-pyspark-demo/blob/master/docker-compose.yml

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    network_mode: host
    ports:
      - "32181:32181"
    expose:
      - "32181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    ports:
      - "29092:29092"
    expose:
      - "29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092

  # spark:
  #   image: jupyter/pyspark-notebook
  #   network_mode: host
  #   links:
  #    - kafka
  #   ports:
  #     - "18888:8888"
